all:
  children:
    network:
      children:
        routers:
          hosts:
            edge-rtr:
              ansible_host: 10.0.0.1
              ansible_network_os: ios
              ansible_connection: network_cli
        firewalls:
          hosts:
            edge-fw:
              ansible_host: 10.0.0.2
              ansible_network_os: panos
              ansible_connection: local
            internal-fw:
              ansible_host: 10.0.1.2
              ansible_network_os: panos
              ansible_connection: local

    servers:
      children:
        dmz:
          hosts:
            web-srv:
              ansible_host: 10.10.1.10
              zone: dmz
        app_tier:
          hosts:
            app-srv:
              ansible_host: 10.10.2.10
              zone: app-tier
        db_tier:
          hosts:
            db-srv:
              ansible_host: 10.10.3.10
              zone: db-tier
        corporate:
          hosts:
            dns-srv:
              ansible_host: 10.10.4.10
              zone: corporate
            vuln-vm:
              ansible_host: 10.10.4.20
              zone: corporate
        management:
          hosts:
            elk-srv:
              ansible_host: 10.10.5.10
              zone: management
            mgmt-vm:
              ansible_host: 10.10.5.20
              zone: management

      vars:
        ansible_user: skg-admin
        ansible_connection: ssh
        ansible_python_interpreter: /usr/bin/python3
